apiVersion: v1
kind: Pod
metadata: 
  name: hostpad-pod
spec: 
  volumes:
  - name: hostpath-vol
    hostPath:
      path: /var/tmp
  containers:
  - name: busybox-container
    image: 'k8s.gcr.io/busybox'
    command: ["/bin/sh", "-c", "echo Hello Team, Thi is a simple File gor HostVolume - $(date) >> /output/output.txt"]
    volumeMounts:
    - name: hostpath-vol
      mountPath: /output 