apiVersion: v1
kind: Pod
metadata: 
  name: lifecycle-demo
spec:
  containers:
  - name: lifecycle-demo-container
    image: nginx
    lifecycle: 
      postStart:
        exec:
          command: ["/bin/sh", "-c", "echo Hello from the postStart handler > /usr/share/message"]
      preStop:
        exec: 
          command: ["/bin/sh", "-c", "nginx -s quit; while kill all -0 nginx; do sleep 1; done"]